#ifndef XAUDAILYFLOW_CONFIG_MQH
#define XAUDAILYFLOW_CONFIG_MQH

#define XDF_MAGIC 360310
#define XDF_MAX_SLIPPAGE_POINTS_DEFAULT 25
#define XDF_ENABLE_MR false
#define XDF_ENABLE_ORB_DIRECT_BREAK false
#define XDF_ENABLE_ORB_TWO_BAR_CONFIRM false
#define XDF_ENABLE_ORB_BREAK_PAUSE_CONTINUE true
#define XDF_ENABLE_ORB_BREAK_RETEST_HOLD true
#define XDF_ORB_ONLY_TREND_CONTINUATION true

#endif
